import Head from 'next/head';

export default function Home() {
  return (
    <div className={'container mx-auto'}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <h1>
        Welcome to{' '}
        <a className={'text-blue-500 hover:underline'} href="https://nextjs.org">Next.js!</a> with{' '}
        <a className={'text-blue-500 hover:underline'} href="https://tailwindcss.com">TailwindCSS</a>
      </h1>
    </div>
  )
}
